updating

diff --git a/.github/workflows/create-ephemeral-dev.yml b/.github/workflows/create-ephemeral-dev.yml
--- a/.github/workflows/create-ephemeral-dev.yml
+++ b/.github/workflows/create-ephemeral-dev.yml
@@ -88,17 +88,17 @@ jobs:
           echo "INSTANCE_IP=$INSTANCE_IP" >> $GITHUB_ENV
           echo "IP Address is: $INSTANCE_IP"
 
-      - name: Add server to known_hosts
-        run: |
-          echo ${{ env.INSTANCE_IP }}
-          set -e  #Ensure the script exits if any command fails
-          mkdir -p ~/.ssh
-          chmod 700 ~/.ssh
-          for i in {1..5}; do
-            ssh-keyscan -H ${{ env.INSTANCE_IP }} >> ~/.ssh/known_hosts && break || { echo "ssh-keyscan failed"; exit 1; }
-            sleep 5
-          done
-          chmod 644 ~/.ssh/known_hosts
+      # - name: Add server to known_hosts
+      #   run: |
+      #     echo ${{ env.INSTANCE_IP }}
+      #     set -e  #Ensure the script exits if any command fails
+      #     mkdir -p ~/.ssh
+      #     chmod 700 ~/.ssh
+      #     for i in {1..5}; do
+      #       ssh-keyscan -H ${{ env.INSTANCE_IP }} >> ~/.ssh/known_hosts && break || { echo "ssh-keyscan failed"; exit 1; }
+      #       sleep 5
+      #     done
+      #     chmod 644 ~/.ssh/known_hosts
 
       - name: Start SSH Agent
         uses: webfactory/ssh-agent@v0.9.0
